#ifndef UNITY_STANDARD_CONFIG_INCLUDED
	#define UNITY_STANDARD_CONFIG_INCLUDED
	
	//mipmap step  * roughness -> mipmap等级
	#ifndef UNITY_SPECCUBE_LOD_STEPS
		#define UNITY_SPECCUBE_LOD_STEPS (6)
	#endif
	
#endif // UNITY_STANDARD_CONFIG_INCLUDED
